{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"makeUIViewController(context:)","externalID":"s:8MediaKit11VideoPlayerV20makeUIViewController7contextAA0cdG0C7SwiftUI0fG20RepresentableContextVyACG_tF","extendedModule":"MediaKit","modules":[{"name":"MediaKit"}],"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeUIViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7SwiftUI29UIViewControllerRepresentableP7Contexta","kind":"typeIdentifier","text":"Context"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@MediaKit@objc(cs)VideoPlayerController","kind":"typeIdentifier","text":"VideoPlayerController"}],"roleHeading":"Instance Method"},"kind":"symbol","identifier":{"url":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer\/makeUIViewController(context:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeUIViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"context"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Context","preciseIdentifier":"s:7SwiftUI29UIViewControllerRepresentableP7Contexta"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@MediaKit@objc(cs)VideoPlayerController","kind":"typeIdentifier","text":"VideoPlayerController","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController"}],"platforms":["tvOS"]}]}],"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIViewControllerRepresentable.makeUIViewController(context:)"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mediakit\/videoplayer\/makeuiviewcontroller(context:)"]}],"references":{"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayer":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayer"}],"navigatorTitle":[{"kind":"identifier","text":"VideoPlayer"}],"role":"symbol","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer","title":"VideoPlayer","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"This view can be used to stream videos."}],"url":"\/documentation\/mediakit\/videoplayer"},"doc://com.kankoda.MediaKit/documentation/MediaKit":{"kind":"symbol","role":"collection","title":"MediaKit","url":"\/documentation\/mediakit","type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit","abstract":[{"type":"text","text":"A SwiftUI library with a video player and other video-related utilities."}]},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerController":{"abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoPlayerController","kind":"identifier"}],"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController","type":"topic","navigatorTitle":[{"text":"VideoPlayerController","kind":"identifier"}],"role":"symbol","title":"VideoPlayerController","url":"\/documentation\/mediakit\/videoplayercontroller"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayer/makeUIViewController(context:)":{"url":"\/documentation\/mediakit\/videoplayer\/makeuiviewcontroller(context:)","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer\/makeUIViewController(context:)","title":"makeUIViewController(context:)","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeUIViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Context","preciseIdentifier":"s:7SwiftUI29UIViewControllerRepresentableP7Contexta","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"VideoPlayerController","preciseIdentifier":"c:@M@MediaKit@objc(cs)VideoPlayerController","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"value":"VideoPlayerController","op":"replace","path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/title"},{"value":[{"kind":"identifier","text":"VideoPlayerController"}],"op":"replace","path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/fragments"},{"value":[{"text":"VideoPlayerController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}