{"sections":[],"abstract":[{"type":"text","text":"A SwiftUI library with a video player and other video-related utilities."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit"},"topicSections":[{"title":"Articles","anchor":"Articles","identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/Getting-Started-Article"]},{"title":"Data","anchor":"Data","identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/SampleVideo"]},{"title":"Models","anchor":"Models","identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/MediaItem"]},{"title":"Pagination","anchor":"Pagination","identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/Paginable","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/PaginationContext"]},{"title":"Video","anchor":"Video","identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerConfiguration","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenConfiguration","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenViewModifier"]},{"title":"Variables","anchor":"Variables","generated":true,"identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VietnameseInputVersionNumber","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VietnameseInputVersionString"]},{"title":"Extended Modules","anchor":"Extended-Modules","generated":true,"identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/SwiftUICore"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mediakit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mediakit"]}],"metadata":{"title":"MediaKit","modules":[{"name":"MediaKit"}],"role":"collection","symbolKind":"module","externalID":"MediaKit","roleHeading":"Framework"},"kind":"symbol","primaryContentSections":[{"content":[{"level":2,"type":"heading","anchor":"Overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"Logo.png"}]},{"type":"paragraph","inlineContent":[{"text":"MediaKit is a SwiftUI library with a configurable ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer"},{"text":" view, and as other video-related functionality like a video splash screen, views, sample data, and Chromecast support.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Unlike AVKit’s VideoPlayer, MediaKit’s "},{"type":"reference","isActive":true,"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer"},{"type":"text","text":" can be configured to great extent. It also lets you observe the current player time and can trigger a custom action when the player reaches the end."}]},{"level":2,"type":"heading","anchor":"Installation","text":"Installation"},{"type":"paragraph","inlineContent":[{"text":"MediaKit can be installed with the Swift Package Manager:","type":"text"}]},{"syntax":null,"type":"codeListing","code":["https:\/\/github.com\/kankoda\/MediaKit.git"]},{"content":[{"inlineContent":[{"text":"For remote playback to work in macOS Catalyst, you must enable “Outgoing Connections (Client)” under “Signing & Capabilities > App Sandbox” and enable “App Transport Security Settings > Allow Arbitrary Loads” (for more security, specify allowed domains) under the app’s “Info” configuration.","type":"text"}],"type":"paragraph"}],"type":"aside","style":"important","name":"Important"},{"level":2,"type":"heading","anchor":"Supported-Platforms","text":"Supported Platforms"},{"type":"paragraph","inlineContent":[{"text":"MediaKit supports iOS 15, macOS Catalyst 12, tvOS 15, visionOS 8, and visionOS 1.","type":"text"}]},{"level":2,"type":"heading","anchor":"Getting-Started","text":"Getting Started"},{"inlineContent":[{"text":"See the ","type":"text"},{"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/Getting-Started-Article","type":"reference","isActive":true},{"text":" and ","type":"text"},{"text":"doc:Chromecast-Article","type":"text"},{"text":" articles for more information.","type":"text"}],"type":"paragraph"},{"text":"Demo Application","anchor":"Demo-Application","type":"heading","level":2},{"inlineContent":[{"text":"The ","type":"text"},{"identifier":"https:\/\/github.com\/kankoda\/MediaKit","isActive":true,"type":"reference"},{"text":" has a demo app that lets you explore the library.","type":"text"}],"type":"paragraph"},{"text":"Repository","anchor":"Repository","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"For more information, source code, etc., visit the "},{"overridingTitle":"project repository","overridingTitleInlineContent":[{"text":"project repository","type":"text"}],"isActive":true,"type":"reference","identifier":"https:\/\/github.com\/kankoda\/MediaKit"},{"type":"text","text":"."}],"type":"paragraph"},{"text":"License","anchor":"License","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"MediaKit is closed source. See the LICENSE file in the "},{"type":"reference","overridingTitleInlineContent":[{"type":"text","text":"main repo"}],"overridingTitle":"main repo","identifier":"https:\/\/github.com\/kankoda\/MediaKit","isActive":true},{"type":"text","text":" for more info."}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[[]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.kankoda.MediaKit/documentation/MediaKit/VietnameseInputVersionString":{"navigatorTitle":[{"kind":"identifier","text":"VietnameseInputVersionString"}],"abstract":[{"text":"Project version string for VietnameseInput.","type":"text"}],"title":"VietnameseInputVersionString","type":"topic","url":"\/documentation\/mediakit\/vietnameseinputversionstring","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"VietnameseInputVersionString"},{"kind":"text","text":": <<error type>>"}],"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VietnameseInputVersionString"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerController":{"abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoPlayerController","kind":"identifier"}],"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController","type":"topic","navigatorTitle":[{"text":"VideoPlayerController","kind":"identifier"}],"role":"symbol","title":"VideoPlayerController","url":"\/documentation\/mediakit\/videoplayercontroller"},"doc://com.kankoda.MediaKit/documentation/MediaKit/Getting-Started-Article":{"role":"article","title":"Getting Started","url":"\/documentation\/mediakit\/getting-started-article","kind":"article","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/Getting-Started-Article","type":"topic","abstract":[{"type":"text","text":"This article describes how to get started with MediaKit."}]},"doc://com.kankoda.MediaKit/documentation/MediaKit/SampleVideo":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SampleVideo","kind":"identifier"}],"url":"\/documentation\/mediakit\/samplevideo","kind":"symbol","navigatorTitle":[{"text":"SampleVideo","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"This struct contains sample videos to use in development."}],"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/SampleVideo","title":"SampleVideo","role":"symbol"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayer":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayer"}],"navigatorTitle":[{"kind":"identifier","text":"VideoPlayer"}],"role":"symbol","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer","title":"VideoPlayer","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"This view can be used to stream videos."}],"url":"\/documentation\/mediakit\/videoplayer"},"doc://com.kankoda.MediaKit/documentation/MediaKit/PaginationContext":{"kind":"symbol","url":"\/documentation\/mediakit\/paginationcontext","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaginationContext"}],"navigatorTitle":[{"kind":"identifier","text":"PaginationContext"}],"abstract":[{"type":"text","text":"This class can be used to manage a paginated data source."}],"type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/PaginationContext","title":"PaginationContext"},"doc://com.kankoda.MediaKit/documentation/MediaKit/Paginable":{"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/Paginable","type":"topic","title":"Paginable","abstract":[{"type":"text","text":"This protocol can be implemented by paginable types."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Paginable"}],"navigatorTitle":[{"kind":"identifier","text":"Paginable"}],"role":"symbol","url":"\/documentation\/mediakit\/paginable"},"doc://com.kankoda.MediaKit/documentation/MediaKit/SwiftUICore":{"kind":"symbol","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/SwiftUICore","type":"topic","title":"SwiftUICore","abstract":[],"role":"collection","url":"\/documentation\/mediakit\/swiftuicore"},"doc://com.kankoda.MediaKit/documentation/MediaKit/MediaItem":{"title":"MediaItem","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"This struct represents a general media item, that can be"},{"type":"text","text":" "},{"type":"text","text":"either a movie, podcast, radio show, etc."}],"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/MediaItem","url":"\/documentation\/mediakit\/mediaitem","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MediaItem","kind":"identifier"}],"navigatorTitle":[{"text":"MediaItem","kind":"identifier"}],"role":"symbol"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoSplashScreenViewModifier":{"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenViewModifier","url":"\/documentation\/mediakit\/videosplashscreenviewmodifier","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoSplashScreenViewModifier","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"VideoSplashScreenViewModifier","abstract":[{"text":"This view modifier can be used to add video-based splash","type":"text"},{"text":" ","type":"text"},{"text":"screens to any view.","type":"text"}],"navigatorTitle":[{"text":"VideoSplashScreenViewModifier","kind":"identifier"}],"type":"topic"},"Logo.png":{"type":"image","identifier":"Logo.png","variants":[{"traits":["1x","light"],"url":"\/images\/com.kankoda.MediaKit\/Logo.png"}],"alt":"Library logotype"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerConfiguration":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayerConfiguration"}],"url":"\/documentation\/mediakit\/videoplayerconfiguration","navigatorTitle":[{"kind":"identifier","text":"VideoPlayerConfiguration"}],"type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerConfiguration","abstract":[{"type":"text","text":"This type can be used to configure a "},{"type":"reference","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer","isActive":true},{"type":"text","text":"."}],"title":"VideoPlayerConfiguration","role":"symbol"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VietnameseInputVersionNumber":{"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VietnameseInputVersionNumber","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Project version number for VietnameseInput."}],"title":"VietnameseInputVersionNumber","url":"\/documentation\/mediakit\/vietnameseinputversionnumber","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VietnameseInputVersionNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","navigatorTitle":[{"text":"VietnameseInputVersionNumber","kind":"identifier"}]},"doc://com.kankoda.MediaKit/documentation/MediaKit":{"kind":"symbol","role":"collection","title":"MediaKit","url":"\/documentation\/mediakit","type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit","abstract":[{"type":"text","text":"A SwiftUI library with a video player and other video-related utilities."}]},"https://github.com/kankoda/MediaKit":{"type":"link","titleInlineContent":[{"type":"text","text":"project repository"}],"identifier":"https:\/\/github.com\/kankoda\/MediaKit","title":"project repository","url":"https:\/\/github.com\/kankoda\/MediaKit"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoSplashScreenConfiguration":{"kind":"symbol","url":"\/documentation\/mediakit\/videosplashscreenconfiguration","title":"VideoSplashScreenConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoSplashScreenConfiguration"}],"abstract":[{"text":"This type can be used to configure a video splash screen.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoSplashScreenConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"title":"Articles","anchor":"Articles","identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/Getting-Started-Article"]},{"title":"Video","anchor":"Video","identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController"]},{"title":"Variables","anchor":"Variables","generated":true,"identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VietnameseInputVersionNumber","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VietnameseInputVersionString"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VietnameseInputVersionString\/title","value":"VietnameseInputVersionString","op":"replace"},{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VietnameseInputVersionString\/fragments","value":[{"kind":"identifier","text":"VietnameseInputVersionString"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/title","value":"VideoPlayerController","op":"replace"},{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/fragments","value":[{"text":"VideoPlayerController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/navigatorTitle","value":[{"text":"VideoPlayerController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VietnameseInputVersionNumber\/title","value":"VietnameseInputVersionNumber","op":"replace"},{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VietnameseInputVersionNumber\/fragments","value":[{"text":"VietnameseInputVersionNumber","kind":"identifier"}],"op":"replace"}]}]}