{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController\/initWithCoder:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":" *) ","kind":"text"},{"text":"coder","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["tvOS"],"languages":["occ"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mediakit\/videoplayercontroller\/initwithcoder:"]}],"metadata":{"externalID":"c:@M@MediaKit@objc(cs)VideoPlayerController(im)initWithCoder:","roleHeading":"Instance Method","title":"initWithCoder:","modules":[{"name":"MediaKit"}],"symbolKind":"method","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController"]]},"references":{"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerController":{"abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoPlayerController","kind":"identifier"}],"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController","type":"topic","navigatorTitle":[{"text":"VideoPlayerController","kind":"identifier"}],"role":"symbol","title":"VideoPlayerController","url":"\/documentation\/mediakit\/videoplayercontroller"},"doc://com.kankoda.MediaKit/documentation/MediaKit":{"kind":"symbol","role":"collection","title":"MediaKit","url":"\/documentation\/mediakit","type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit","abstract":[{"type":"text","text":"A SwiftUI library with a video player and other video-related utilities."}]},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerController/initWithCoder:":{"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","title":"initWithCoder:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"url":"\/documentation\/mediakit\/videoplayercontroller\/initwithcoder:","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController\/initWithCoder:","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/title","op":"replace","value":"VideoPlayerController"},{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/fragments","op":"replace","value":[{"text":"VideoPlayerController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/navigatorTitle","op":"replace","value":[{"text":"VideoPlayerController","kind":"identifier"}]}]}]}