{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController"]]},"metadata":{"navigatorTitle":[{"text":"player","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@MediaKit@objc(cs)VideoPlayerController(py)player","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVPlayer","text":"AVPlayer","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"player","modules":[{"name":"MediaKit"}],"roleHeading":"Instance Property","role":"symbol"},"identifier":{"url":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController\/player","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVPlayer","preciseIdentifier":"c:objc(cs)AVPlayer"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["tvOS"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/mediakit\/videoplayercontroller\/player"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mediakit\/videoplayercontroller\/player"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerController":{"abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoPlayerController","kind":"identifier"}],"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController","type":"topic","navigatorTitle":[{"text":"VideoPlayerController","kind":"identifier"}],"role":"symbol","title":"VideoPlayerController","url":"\/documentation\/mediakit\/videoplayercontroller"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerController/player":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVPlayer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayer"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"player","kind":"identifier"}],"abstract":[],"url":"\/documentation\/mediakit\/videoplayercontroller\/player","type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController\/player","role":"symbol","title":"player"},"doc://com.kankoda.MediaKit/documentation/MediaKit":{"kind":"symbol","role":"collection","title":"MediaKit","url":"\/documentation\/mediakit","type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit","abstract":[{"type":"text","text":"A SwiftUI library with a video player and other video-related utilities."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"player","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"player","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)AVPlayer","kind":"typeIdentifier","text":"AVPlayer"},{"kind":"text","text":" * "},{"kind":"identifier","text":"player"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["tvOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/title","value":"VideoPlayerController","op":"replace"},{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/fragments","value":[{"kind":"identifier","text":"VideoPlayerController"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/navigatorTitle","value":[{"kind":"identifier","text":"VideoPlayerController"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController~1player\/title","op":"replace","value":"player"},{"op":"replace","value":[{"kind":"identifier","text":"player"}],"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController~1player\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}