{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer"},"topicSections":[{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer\/init(videoURL:time:configuration:controllerConfiguration:didPlayToEndAction:)"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer\/withBackground(_:)"],"generated":true},{"title":"Type Aliases","anchor":"Type-Aliases","identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer\/Action"],"generated":true},{"title":"Type Properties","anchor":"Type-Properties","identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer\/sampleVideoURL","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer\/sampleVideoURLString"],"generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer\/UIViewControllerRepresentable-Implementations","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer\/View-Implementations","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer\/View-Implementations"],"generated":true}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mediakit\/videoplayer"]}],"abstract":[{"type":"text","text":"This view can be used to stream videos."}],"metadata":{"title":"VideoPlayer","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoPlayer","kind":"identifier"}],"roleHeading":"Structure","modules":[{"name":"MediaKit"}],"navigatorTitle":[{"kind":"identifier","text":"VideoPlayer"}],"symbolKind":"struct","externalID":"s:8MediaKit11VideoPlayerV"},"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.kankoda.MediaKit\/s8SendableP","doc:\/\/com.kankoda.MediaKit\/7SwiftUI29UIViewControllerRepresentableP","doc:\/\/com.kankoda.MediaKit\/7SwiftUI4ViewP"],"kind":"relationships","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit"]]},"kind":"symbol","seeAlsoSections":[{"title":"Video","anchor":"Video","identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerConfiguration","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenConfiguration","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenViewModifier"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoPlayer","kind":"identifier"}],"platforms":["tvOS"],"languages":["swift"]}]},{"content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"This view wraps a ","type":"text"},{"code":"VideoPlayerController","type":"codeVoice"},{"text":" and loads urls","type":"text"},{"text":" ","type":"text"},{"text":"into an ","type":"text"},{"code":"AVPlayer","type":"codeVoice"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"You can inject an optional ","type":"text"},{"type":"codeVoice","code":"time"},{"text":" binding, to keep track","type":"text"},{"text":" ","type":"text"},{"text":"of the player time. You can persist this value to resume","type":"text"},{"text":" ","type":"text"},{"text":"playback later. You can inject a ","type":"text"},{"type":"codeVoice","code":"didPlayToEndAction"},{"text":" to","type":"text"},{"text":" ","type":"text"},{"text":"be triggered when the player reaches the end.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can inject a custom "},{"code":"configuration","type":"codeVoice"},{"type":"text","text":" to customize the"},{"type":"text","text":" "},{"type":"text","text":"video player and a custom "},{"code":"controllerConfiguration","type":"codeVoice"},{"type":"text","text":" that"},{"type":"text","text":" "},{"type":"text","text":"can customize the video player controller."}]}],"kind":"content"}],"references":{"doc://com.kankoda.MediaKit/documentation/MediaKit":{"kind":"symbol","role":"collection","title":"MediaKit","url":"\/documentation\/mediakit","type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit","abstract":[{"type":"text","text":"A SwiftUI library with a video player and other video-related utilities."}]},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoSplashScreenViewModifier":{"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenViewModifier","url":"\/documentation\/mediakit\/videosplashscreenviewmodifier","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoSplashScreenViewModifier","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"VideoSplashScreenViewModifier","abstract":[{"text":"This view modifier can be used to add video-based splash","type":"text"},{"text":" ","type":"text"},{"text":"screens to any view.","type":"text"}],"navigatorTitle":[{"text":"VideoSplashScreenViewModifier","kind":"identifier"}],"type":"topic"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoSplashScreenConfiguration":{"kind":"symbol","url":"\/documentation\/mediakit\/videosplashscreenconfiguration","title":"VideoSplashScreenConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoSplashScreenConfiguration"}],"abstract":[{"text":"This type can be used to configure a video splash screen.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoSplashScreenConfiguration"}]},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayer/sampleVideoURL":{"title":"sampleVideoURL","kind":"symbol","type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer\/sampleVideoURL","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sampleVideoURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?"}],"abstract":[{"text":"A sample video URL that can be used to test the view.","type":"text"}],"url":"\/documentation\/mediakit\/videoplayer\/samplevideourl","role":"symbol"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayer/Action":{"title":"VideoPlayer.Action","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"Action"}],"kind":"symbol","url":"\/documentation\/mediakit\/videoplayer\/action","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer\/Action","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Action"}]},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerController":{"abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoPlayerController","kind":"identifier"}],"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController","type":"topic","navigatorTitle":[{"text":"VideoPlayerController","kind":"identifier"}],"role":"symbol","title":"VideoPlayerController","url":"\/documentation\/mediakit\/videoplayercontroller"},"doc://com.kankoda.MediaKit/7SwiftUI29UIViewControllerRepresentableP":{"identifier":"doc:\/\/com.kankoda.MediaKit\/7SwiftUI29UIViewControllerRepresentableP","type":"unresolvable","title":"SwiftUI.UIViewControllerRepresentable"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayer/withBackground(_:)":{"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withBackground","kind":"identifier"},{"text":"<","kind":"text"},{"text":"Content","kind":"genericParameter"},{"text":">(","kind":"text"},{"preciseIdentifier":"s:8MediaKit11VideoPlayerV14withBackgroundyQrx7SwiftUI4ViewRzlFQO7Contentxmfp","text":"Content","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"some","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:7SwiftUI4ViewP","text":"View","kind":"typeIdentifier"}],"url":"\/documentation\/mediakit\/videoplayer\/withbackground(_:)","abstract":[{"type":"text","text":"Add a greedy background to the video player."}],"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer\/withBackground(_:)","title":"withBackground(_:)","kind":"symbol"},"doc://com.kankoda.MediaKit/7SwiftUI4ViewP":{"identifier":"doc:\/\/com.kankoda.MediaKit\/7SwiftUI4ViewP","title":"SwiftUICore.View","type":"unresolvable"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayer/UIViewControllerRepresentable-Implementations":{"title":"UIViewControllerRepresentable Implementations","type":"topic","role":"collectionGroup","abstract":[],"kind":"article","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer\/UIViewControllerRepresentable-Implementations","url":"\/documentation\/mediakit\/videoplayer\/uiviewcontrollerrepresentable-implementations"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayer":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayer"}],"navigatorTitle":[{"kind":"identifier","text":"VideoPlayer"}],"role":"symbol","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer","title":"VideoPlayer","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"This view can be used to stream videos."}],"url":"\/documentation\/mediakit\/videoplayer"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayer/sampleVideoURLString":{"type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer\/sampleVideoURLString","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sampleVideoURLString","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/mediakit\/videoplayer\/samplevideourlstring","kind":"symbol","abstract":[{"text":"A sample video URL that can be used to test the view.","type":"text"}],"title":"sampleVideoURLString","role":"symbol"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayer/View-Implementations":{"type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer\/View-Implementations","kind":"article","url":"\/documentation\/mediakit\/videoplayer\/view-implementations","role":"collectionGroup","title":"View Implementations","abstract":[]},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerConfiguration":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayerConfiguration"}],"url":"\/documentation\/mediakit\/videoplayerconfiguration","navigatorTitle":[{"kind":"identifier","text":"VideoPlayerConfiguration"}],"type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerConfiguration","abstract":[{"type":"text","text":"This type can be used to configure a "},{"type":"reference","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer","isActive":true},{"type":"text","text":"."}],"title":"VideoPlayerConfiguration","role":"symbol"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayer/init(videoURL:time:configuration:controllerConfiguration:didPlayToEndAction:)":{"kind":"symbol","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer\/init(videoURL:time:configuration:controllerConfiguration:didPlayToEndAction:)","abstract":[{"type":"text","text":"Create a video player."}],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"videoURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"time"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI7BindingV","text":"Binding"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":">?, "},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:8MediaKit24VideoPlayerConfigurationV","text":"VideoPlayerConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"controllerConfiguration"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MediaKit@objc(cs)VideoPlayerController","text":"VideoPlayerController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didPlayToEndAction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:8MediaKit11VideoPlayerV6Actiona","text":"Action"},{"kind":"text","text":"?)"}],"title":"init(videoURL:time:configuration:controllerConfiguration:didPlayToEndAction:)","role":"symbol","url":"\/documentation\/mediakit\/videoplayer\/init(videourl:time:configuration:controllerconfiguration:didplaytoendaction:)"},"doc://com.kankoda.MediaKit/s8SendableP":{"identifier":"doc:\/\/com.kankoda.MediaKit\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/title","value":"VideoPlayerController"},{"op":"replace","path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/fragments","value":[{"text":"VideoPlayerController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/navigatorTitle","value":[{"text":"VideoPlayerController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}