{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["tvOS"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoSplashScreenConfiguration","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mediakit\/videosplashscreenconfiguration"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenConfiguration"},"metadata":{"modules":[{"name":"MediaKit"}],"navigatorTitle":[{"text":"VideoSplashScreenConfiguration","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoSplashScreenConfiguration","kind":"identifier"}],"role":"symbol","symbolKind":"struct","externalID":"s:8MediaKit30VideoSplashScreenConfigurationV","roleHeading":"Structure","title":"VideoSplashScreenConfiguration"},"abstract":[{"type":"text","text":"This type can be used to configure a video splash screen."}],"topicSections":[{"identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenConfiguration\/init(dismissAnimation:maxDisplayDuration:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenConfiguration\/dismissAnimation","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenConfiguration\/maxDisplayDuration"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenConfiguration\/standard"],"anchor":"Type-Properties","title":"Type Properties","generated":true}],"relationshipsSections":[{"identifiers":["doc:\/\/com.kankoda.MediaKit\/s8SendableP"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerConfiguration","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenViewModifier"],"anchor":"Video","title":"Video","generated":true}],"references":{"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayer":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayer"}],"navigatorTitle":[{"kind":"identifier","text":"VideoPlayer"}],"role":"symbol","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer","title":"VideoPlayer","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"This view can be used to stream videos."}],"url":"\/documentation\/mediakit\/videoplayer"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoSplashScreenViewModifier":{"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenViewModifier","url":"\/documentation\/mediakit\/videosplashscreenviewmodifier","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoSplashScreenViewModifier","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"VideoSplashScreenViewModifier","abstract":[{"text":"This view modifier can be used to add video-based splash","type":"text"},{"text":" ","type":"text"},{"text":"screens to any view.","type":"text"}],"navigatorTitle":[{"text":"VideoSplashScreenViewModifier","kind":"identifier"}],"type":"topic"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoSplashScreenConfiguration":{"kind":"symbol","url":"\/documentation\/mediakit\/videosplashscreenconfiguration","title":"VideoSplashScreenConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoSplashScreenConfiguration"}],"abstract":[{"text":"This type can be used to configure a video splash screen.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoSplashScreenConfiguration"}]},"doc://com.kankoda.MediaKit/documentation/MediaKit":{"kind":"symbol","role":"collection","title":"MediaKit","url":"\/documentation\/mediakit","type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit","abstract":[{"type":"text","text":"A SwiftUI library with a video player and other video-related utilities."}]},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerConfiguration":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayerConfiguration"}],"url":"\/documentation\/mediakit\/videoplayerconfiguration","navigatorTitle":[{"kind":"identifier","text":"VideoPlayerConfiguration"}],"type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerConfiguration","abstract":[{"type":"text","text":"This type can be used to configure a "},{"type":"reference","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer","isActive":true},{"type":"text","text":"."}],"title":"VideoPlayerConfiguration","role":"symbol"},"doc://com.kankoda.MediaKit/s8SendableP":{"identifier":"doc:\/\/com.kankoda.MediaKit\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoSplashScreenConfiguration/dismissAnimation":{"kind":"symbol","abstract":[{"type":"text","text":"The video content mode to use."}],"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenConfiguration\/dismissAnimation","role":"symbol","title":"dismissAnimation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dismissAnimation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Animation","preciseIdentifier":"s:7SwiftUI9AnimationV"}],"type":"topic","url":"\/documentation\/mediakit\/videosplashscreenconfiguration\/dismissanimation"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerController":{"abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoPlayerController","kind":"identifier"}],"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController","type":"topic","navigatorTitle":[{"text":"VideoPlayerController","kind":"identifier"}],"role":"symbol","title":"VideoPlayerController","url":"\/documentation\/mediakit\/videoplayercontroller"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoSplashScreenConfiguration/maxDisplayDuration":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxDisplayDuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"type":"text","text":"The max seconds that the splash screen is presented."}],"kind":"symbol","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenConfiguration\/maxDisplayDuration","type":"topic","role":"symbol","url":"\/documentation\/mediakit\/videosplashscreenconfiguration\/maxdisplayduration","title":"maxDisplayDuration"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoSplashScreenConfiguration/standard":{"abstract":[{"text":"The standard video splash screen configuration.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/mediakit\/videosplashscreenconfiguration\/standard","type":"topic","title":"standard","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standard","kind":"identifier"},{"text":": ","kind":"text"},{"text":"VideoSplashScreenConfiguration","kind":"typeIdentifier","preciseIdentifier":"s:8MediaKit30VideoSplashScreenConfigurationV"}],"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenConfiguration\/standard"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoSplashScreenConfiguration/init(dismissAnimation:maxDisplayDuration:)":{"kind":"symbol","abstract":[{"type":"text","text":"Create a custom video splash screen configuration."}],"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenConfiguration\/init(dismissAnimation:maxDisplayDuration:)","url":"\/documentation\/mediakit\/videosplashscreenconfiguration\/init(dismissanimation:maxdisplayduration:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dismissAnimation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Animation","preciseIdentifier":"s:7SwiftUI9AnimationV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxDisplayDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","title":"init(dismissAnimation:maxDisplayDuration:)"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/title","value":"VideoPlayerController","op":"replace"},{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/fragments","value":[{"text":"VideoPlayerController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/navigatorTitle","op":"replace","value":[{"text":"VideoPlayerController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}