{"metadata":{"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayerController"}],"role":"symbol","title":"VideoPlayerController","roleHeading":"Class","externalID":"c:@M@MediaKit@objc(cs)VideoPlayerController","modules":[{"name":"MediaKit"}],"navigatorTitle":[{"kind":"identifier","text":"VideoPlayerController"}]},"kind":"symbol","identifier":{"url":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.kankoda.MediaKit\/objc(cs)AVPlayerViewController"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.kankoda.MediaKit\/objc(pl)NSCoding","doc:\/\/com.kankoda.MediaKit\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.kankoda.MediaKit\/objc(pl)NSObject","doc:\/\/com.kankoda.MediaKit\/s7CVarArgP","doc:\/\/com.kankoda.MediaKit\/s28CustomDebugStringConvertibleP","doc:\/\/com.kankoda.MediaKit\/s23CustomStringConvertibleP","doc:\/\/com.kankoda.MediaKit\/SQ","doc:\/\/com.kankoda.MediaKit\/SH","doc:\/\/com.kankoda.MediaKit\/objc(pl)UIAppearanceContainer","doc:\/\/com.kankoda.MediaKit\/objc(pl)UIContentContainer","doc:\/\/com.kankoda.MediaKit\/objc(pl)UIFocusEnvironment","doc:\/\/com.kankoda.MediaKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.kankoda.MediaKit\/objc(pl)UIStateRestoring","doc:\/\/com.kankoda.MediaKit\/5UIKit23UITraitChangeObservableP","doc:\/\/com.kankoda.MediaKit\/objc(pl)UITraitEnvironment","doc:\/\/com.kankoda.MediaKit\/objc(pl)UIUserActivityRestoring"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"seeAlsoSections":[{"title":"Video","generated":true,"anchor":"Video","identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerConfiguration","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenConfiguration","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenViewModifier"]}],"primaryContentSections":[{"declarations":[{"platforms":["tvOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoPlayerController","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController\/player"]}],"variants":[{"paths":["\/documentation\/mediakit\/videoplayercontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mediakit\/videoplayercontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerController/initWithCoder:":{"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","title":"initWithCoder:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"url":"\/documentation\/mediakit\/videoplayercontroller\/initwithcoder:","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController\/initWithCoder:","role":"symbol"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerController/player":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"player","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVPlayer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVPlayer"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"player","kind":"identifier"}],"abstract":[],"url":"\/documentation\/mediakit\/videoplayercontroller\/player","type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController\/player","role":"symbol","title":"player"},"doc://com.kankoda.MediaKit/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/com.kankoda.MediaKit\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoSplashScreenViewModifier":{"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenViewModifier","url":"\/documentation\/mediakit\/videosplashscreenviewmodifier","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoSplashScreenViewModifier","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"VideoSplashScreenViewModifier","abstract":[{"text":"This view modifier can be used to add video-based splash","type":"text"},{"text":" ","type":"text"},{"text":"screens to any view.","type":"text"}],"navigatorTitle":[{"text":"VideoSplashScreenViewModifier","kind":"identifier"}],"type":"topic"},"doc://com.kankoda.MediaKit/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","type":"unresolvable","identifier":"doc:\/\/com.kankoda.MediaKit\/objc(pl)NSExtensionRequestHandling"},"doc://com.kankoda.MediaKit/documentation/MediaKit":{"kind":"symbol","role":"collection","title":"MediaKit","url":"\/documentation\/mediakit","type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit","abstract":[{"type":"text","text":"A SwiftUI library with a video player and other video-related utilities."}]},"doc://com.kankoda.MediaKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.kankoda.MediaKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.kankoda.MediaKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.kankoda.MediaKit\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://com.kankoda.MediaKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.kankoda.MediaKit\/SQ","title":"Swift.Equatable"},"doc://com.kankoda.MediaKit/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/com.kankoda.MediaKit\/objc(pl)UIFocusEnvironment"},"doc://com.kankoda.MediaKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.kankoda.MediaKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.kankoda.MediaKit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.kankoda.MediaKit\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://com.kankoda.MediaKit/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/com.kankoda.MediaKit\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://com.kankoda.MediaKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.kankoda.MediaKit\/s28CustomDebugStringConvertibleP"},"doc://com.kankoda.MediaKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/com.kankoda.MediaKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://com.kankoda.MediaKit/SH":{"identifier":"doc:\/\/com.kankoda.MediaKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.kankoda.MediaKit/objc(cs)AVPlayerViewController":{"type":"unresolvable","identifier":"doc:\/\/com.kankoda.MediaKit\/objc(cs)AVPlayerViewController","title":"AVPlayerViewController"},"doc://com.kankoda.MediaKit/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/com.kankoda.MediaKit\/objc(pl)UIUserActivityRestoring"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerController":{"abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoPlayerController","kind":"identifier"}],"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController","type":"topic","navigatorTitle":[{"text":"VideoPlayerController","kind":"identifier"}],"role":"symbol","title":"VideoPlayerController","url":"\/documentation\/mediakit\/videoplayercontroller"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoSplashScreenConfiguration":{"kind":"symbol","url":"\/documentation\/mediakit\/videosplashscreenconfiguration","title":"VideoSplashScreenConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoSplashScreenConfiguration"}],"abstract":[{"text":"This type can be used to configure a video splash screen.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoSplashScreenConfiguration"}]},"doc://com.kankoda.MediaKit/objc(pl)UIStateRestoring":{"type":"unresolvable","identifier":"doc:\/\/com.kankoda.MediaKit\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerController/initWithNibName:bundle:":{"navigatorTitle":[{"text":"initWithNibName:bundle:","kind":"identifier"}],"kind":"symbol","type":"topic","title":"initWithNibName:bundle:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithNibName:bundle:","kind":"identifier"}],"url":"\/documentation\/mediakit\/videoplayercontroller\/initwithnibname:bundle:","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController\/initWithNibName:bundle:","role":"symbol"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerConfiguration":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayerConfiguration"}],"url":"\/documentation\/mediakit\/videoplayerconfiguration","navigatorTitle":[{"kind":"identifier","text":"VideoPlayerConfiguration"}],"type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerConfiguration","abstract":[{"type":"text","text":"This type can be used to configure a "},{"type":"reference","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer","isActive":true},{"type":"text","text":"."}],"title":"VideoPlayerConfiguration","role":"symbol"},"doc://com.kankoda.MediaKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/com.kankoda.MediaKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayer":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayer"}],"navigatorTitle":[{"kind":"identifier","text":"VideoPlayer"}],"role":"symbol","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer","title":"VideoPlayer","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"This view can be used to stream videos."}],"url":"\/documentation\/mediakit\/videoplayer"},"doc://com.kankoda.MediaKit/s7CVarArgP":{"identifier":"doc:\/\/com.kankoda.MediaKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"VideoPlayerController"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"VideoPlayerController"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"VideoPlayerController","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController\/player"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController\/initWithCoder:","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController\/initWithNibName:bundle:"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.kankoda.MediaKit\/objc(cs)AVPlayerViewController"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"replace","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayerController"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)AVPlayerViewController","kind":"typeIdentifier","text":"AVPlayerViewController"}],"platforms":["tvOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController~1player\/title","value":"player","op":"replace"},{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController~1player\/fragments","value":[{"kind":"identifier","text":"player"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/title","value":"VideoPlayerController","op":"replace"},{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/fragments","value":[{"kind":"identifier","text":"VideoPlayerController"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/navigatorTitle","value":[{"text":"VideoPlayerController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}