{"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayerConfiguration"}],"modules":[{"name":"MediaKit"}],"externalID":"s:8MediaKit24VideoPlayerConfigurationV","navigatorTitle":[{"kind":"identifier","text":"VideoPlayerConfiguration"}],"symbolKind":"struct","title":"VideoPlayerConfiguration","roleHeading":"Structure"},"hierarchy":{"paths":[["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit"]]},"topicSections":[{"identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerConfiguration\/init(autoPlay:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerConfiguration\/autoPlay"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerConfiguration\/list","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerConfiguration\/standard"],"anchor":"Type-Properties","generated":true,"title":"Type Properties"}],"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenConfiguration","doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenViewModifier"],"anchor":"Video","generated":true,"title":"Video"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerConfiguration"},"primaryContentSections":[{"declarations":[{"platforms":["tvOS"],"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoPlayerConfiguration","kind":"identifier"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"This type can be used to configure a "},{"type":"reference","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer","isActive":true},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mediakit\/videoplayerconfiguration"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.kankoda.MediaKit\/s8SendableP"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayer":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayer"}],"navigatorTitle":[{"kind":"identifier","text":"VideoPlayer"}],"role":"symbol","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer","title":"VideoPlayer","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"This view can be used to stream videos."}],"url":"\/documentation\/mediakit\/videoplayer"},"doc://com.kankoda.MediaKit/documentation/MediaKit":{"kind":"symbol","role":"collection","title":"MediaKit","url":"\/documentation\/mediakit","type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit","abstract":[{"type":"text","text":"A SwiftUI library with a video player and other video-related utilities."}]},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerConfiguration/autoPlay":{"title":"autoPlay","kind":"symbol","type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerConfiguration\/autoPlay","url":"\/documentation\/mediakit\/videoplayerconfiguration\/autoplay","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoPlay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Whether to auto-play video when the player appears."}]},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerController":{"abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoPlayerController","kind":"identifier"}],"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerController","type":"topic","navigatorTitle":[{"text":"VideoPlayerController","kind":"identifier"}],"role":"symbol","title":"VideoPlayerController","url":"\/documentation\/mediakit\/videoplayercontroller"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerConfiguration":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoPlayerConfiguration"}],"url":"\/documentation\/mediakit\/videoplayerconfiguration","navigatorTitle":[{"kind":"identifier","text":"VideoPlayerConfiguration"}],"type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerConfiguration","abstract":[{"type":"text","text":"This type can be used to configure a "},{"type":"reference","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayer","isActive":true},{"type":"text","text":"."}],"title":"VideoPlayerConfiguration","role":"symbol"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoSplashScreenViewModifier":{"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenViewModifier","url":"\/documentation\/mediakit\/videosplashscreenviewmodifier","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VideoSplashScreenViewModifier","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"VideoSplashScreenViewModifier","abstract":[{"text":"This view modifier can be used to add video-based splash","type":"text"},{"text":" ","type":"text"},{"text":"screens to any view.","type":"text"}],"navigatorTitle":[{"text":"VideoSplashScreenViewModifier","kind":"identifier"}],"type":"topic"},"doc://com.kankoda.MediaKit/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.kankoda.MediaKit\/s8SendableP","title":"Swift.Sendable"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoSplashScreenConfiguration":{"kind":"symbol","url":"\/documentation\/mediakit\/videosplashscreenconfiguration","title":"VideoSplashScreenConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VideoSplashScreenConfiguration"}],"abstract":[{"text":"This type can be used to configure a video splash screen.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoSplashScreenConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"VideoSplashScreenConfiguration"}]},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerConfiguration/list":{"kind":"symbol","role":"symbol","title":"list","abstract":[{"text":"A list-specific video player configuration with auto","type":"text"},{"text":" ","type":"text"},{"text":"play disabled.","type":"text"}],"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerConfiguration\/list","type":"topic","url":"\/documentation\/mediakit\/videoplayerconfiguration\/list","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"list","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8MediaKit24VideoPlayerConfigurationV","text":"VideoPlayerConfiguration","kind":"typeIdentifier"}]},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerConfiguration/standard":{"type":"topic","abstract":[{"type":"text","text":"The standard video player configuration."}],"title":"standard","url":"\/documentation\/mediakit\/videoplayerconfiguration\/standard","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"standard"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8MediaKit24VideoPlayerConfigurationV","kind":"typeIdentifier","text":"VideoPlayerConfiguration"}],"kind":"symbol","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerConfiguration\/standard","role":"symbol"},"doc://com.kankoda.MediaKit/documentation/MediaKit/VideoPlayerConfiguration/init(autoPlay:)":{"kind":"symbol","title":"init(autoPlay:)","role":"symbol","abstract":[{"type":"text","text":"Create a custom video player configuration."}],"url":"\/documentation\/mediakit\/videoplayerconfiguration\/init(autoplay:)","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VideoPlayerConfiguration\/init(autoPlay:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"autoPlay"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"VideoPlayerController","op":"replace","path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/title"},{"value":[{"text":"VideoPlayerController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/fragments"},{"value":[{"text":"VideoPlayerController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VideoPlayerController\/navigatorTitle"}]}]}