{"variants":[{"paths":["\/documentation\/mediakit\/vietnameseinputversionstring"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/mediakit\/vietnameseinputversionstring"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VietnameseInputVersionString"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VietnameseInputVersionString","kind":"identifier"},{"text":": <<error type>>","kind":"text"}],"platforms":["tvOS"]}]}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"VietnameseInputVersionString"}],"roleHeading":"Global Variable","modules":[{"name":"MediaKit"}],"symbolKind":"var","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"VietnameseInputVersionString"},{"kind":"text","text":": <<error type>>"}],"externalID":"c:@VietnameseInputVersionString","title":"VietnameseInputVersionString"},"abstract":[{"type":"text","text":"Project version string for VietnameseInput."}],"references":{"doc://com.kankoda.MediaKit/documentation/MediaKit/VietnameseInputVersionString":{"navigatorTitle":[{"kind":"identifier","text":"VietnameseInputVersionString"}],"abstract":[{"text":"Project version string for VietnameseInput.","type":"text"}],"title":"VietnameseInputVersionString","type":"topic","url":"\/documentation\/mediakit\/vietnameseinputversionstring","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"VietnameseInputVersionString"},{"kind":"text","text":": <<error type>>"}],"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VietnameseInputVersionString"},"doc://com.kankoda.MediaKit/documentation/MediaKit":{"kind":"symbol","role":"collection","title":"MediaKit","url":"\/documentation\/mediakit","type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit","abstract":[{"type":"text","text":"A SwiftUI library with a video player and other video-related utilities."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"VietnameseInputVersionString"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"VietnameseInputVersionString","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["tvOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"unsigned char","preciseIdentifier":"c:c"},{"kind":"text","text":" "},{"kind":"identifier","text":"VietnameseInputVersionString"},{"kind":"text","text":"[];"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VietnameseInputVersionString\/title","value":"VietnameseInputVersionString"},{"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VietnameseInputVersionString\/fragments","op":"replace","value":[{"kind":"identifier","text":"VietnameseInputVersionString"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}