{"hierarchy":{"paths":[["doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit"]]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Project version number for VietnameseInput.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mediakit\/vietnameseinputversionnumber"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/mediakit\/vietnameseinputversionnumber"]}],"identifier":{"url":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VietnameseInputVersionNumber","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VietnameseInputVersionNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["tvOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"var","role":"symbol","roleHeading":"Global Variable","title":"VietnameseInputVersionNumber","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VietnameseInputVersionNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"modules":[{"name":"MediaKit"}],"externalID":"c:@VietnameseInputVersionNumber","navigatorTitle":[{"text":"VietnameseInputVersionNumber","kind":"identifier"}]},"references":{"doc://com.kankoda.MediaKit/documentation/MediaKit/VietnameseInputVersionNumber":{"identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit\/VietnameseInputVersionNumber","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Project version number for VietnameseInput."}],"title":"VietnameseInputVersionNumber","url":"\/documentation\/mediakit\/vietnameseinputversionnumber","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"VietnameseInputVersionNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic","navigatorTitle":[{"text":"VietnameseInputVersionNumber","kind":"identifier"}]},"doc://com.kankoda.MediaKit/documentation/MediaKit":{"kind":"symbol","role":"collection","title":"MediaKit","url":"\/documentation\/mediakit","type":"topic","identifier":"doc:\/\/com.kankoda.MediaKit\/documentation\/MediaKit","abstract":[{"type":"text","text":"A SwiftUI library with a video player and other video-related utilities."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"op":"replace","value":"VietnameseInputVersionNumber","path":"\/metadata\/title"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"VietnameseInputVersionNumber","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["tvOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"VietnameseInputVersionNumber","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"VietnameseInputVersionNumber","path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VietnameseInputVersionNumber\/title"},{"op":"replace","value":[{"kind":"identifier","text":"VietnameseInputVersionNumber"}],"path":"\/references\/doc:~1~1com.kankoda.MediaKit~1documentation~1MediaKit~1VietnameseInputVersionNumber\/fragments"}]}]}